spring.application.name=picanounon-back

# Server Port
server.port=8080

# Database Configuration (SQLite)
spring.datasource.url=jdbc:sqlite:picanounon.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Tides Configuration
app.tides.watch-dir=data/mareas

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
